/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app_safe (void);
GtkWidget* create_dialog_edit_passitem (void);
GtkWidget* create_dialog_password (void);
GtkWidget* create_dialog_password_gen (void);
GtkWidget* create_dialog_cpw (void);
GtkWidget* create_dialog_launcher (void);
GtkWidget* create_dialog_about (void);
GtkWidget* create_dialog_preferences (void);
GtkWidget* create_context_menu (void);
GtkWidget* create_window_entropy (void);
GtkWidget* create_tray_menu (void);
GtkWidget* create_toolbar_menu (void);
